name: executor
description: >
  Executes async tasks concurrently with a configurable parallelism limit.
  This is an alternative implementation of package `pool` with fewer tests but
  with streaming support.
version: 0.0.3
author: Istvan Soos <istvan.soos@agilord.com>

homepage: https://github.com/agilord/executor

environment:
  sdk: '>=1.0.0 <2.0.0'
