name: executor
description: >
  Executes async tasks with a configurable maximum concurrency and rate.
version: 2.2.4
homepage: https://github.com/agilord/executor
topics:
  - concurrency
  - parallelism
  - execution
  - async
  - rate-limit

environment:
  sdk: '^3.0.0'

dependencies:
  stack_trace: '>=1.9.0 <2.0.0'

dev_dependencies:
  lints: ^4.0.0
  test: ^1.3.0
