name: executor
description: >
  Executes async tasks with a configurable maximum concurrency and rate.
version: 2.2.3
homepage: https://github.com/agilord/executor

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  stack_trace: '>=1.9.0 <2.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.3.0
