name: executor
description: >
  Executes async tasks with a configurable maximum concurrency and rate.
version: 2.0.0
author: Istvan Soos <istvan.soos@agilord.com>

homepage: https://github.com/agilord/executor

environment:
  sdk: ">=2.0.0 <3.0.0"

dev_dependencies:
  test: ^1.3.0
