name: executor
description: >
  Executes async tasks concurrently with a configurable parallelism and start-rate limit.
version: 0.1.0
author: Istvan Soos <istvan.soos@agilord.com>

homepage: https://github.com/agilord/executor

environment:
  sdk: '>=1.0.0 <2.0.0'
